// Generated by CoffeeScript 1.12.1
(function() {
  var IndexLoaderByCheerio, cheerio, fs;

  cheerio = require('cheerio');

  fs = require('fs');

  IndexLoaderByCheerio = (function() {
    function IndexLoaderByCheerio(path) {
      this.path = path;
      this.selector = cheerio.load(fs.readFileSync(path));
    }

    IndexLoaderByCheerio.prototype.write = function() {
      return fs.writeFileSync(this.path, this.selector.html(), 'utf8');
    };

    IndexLoaderByCheerio.prototype.add = function(loader) {
      var html, tagsHTML;
      tagsHTML = loader.tags().split(/,/g).map(function(t) {
        return "<li>" + t + "</li>";
      }).join('\n');
      tagsHTML = "<ul>\n" + tagsHTML + "\n</ul>";
      html = "<article>\n    <h2><a href=\"" + (loader.path()) + "\">" + (loader.title()) + "</a></h2>\n    <small class=\"date\">" + (loader.date()) + "</small>\n    <p>\n    " + (loader.description()) + "\n    </p>\n    " + tagsHTML + "\n</article>";
      return this.selector(html + "\n<hr>\n").insertAfter('h1');
    };

    IndexLoaderByCheerio.prototype.clear = function() {
      var $body, $h1;
      $h1 = this.selector('h1');
      $body = this.selector('body');
      $body.empty();
      return $body.append($h1);
    };

    return IndexLoaderByCheerio;

  })();

  module.exports = IndexLoaderByCheerio;

}).call(this);
