// Generated by CoffeeScript 1.12.1
(function() {
  var HTMLLoader, TextLoader, createTemplateLoader, err, filePath, fs, htmlLoader, marked, textLoader;

  fs = require('fs');

  HTMLLoader = require('FileLoaderCheerio');

  marked = require('marked');

  filePath = (function() {
    var html, name, template, text;
    name = process.argv.slice(-1);
    text = "../text/" + name + ".txt";
    html = "../" + name + ".html";
    template = 'template.html';
    return {
      text: text,
      html: html
    };
  })();

  TextLoader = (function() {
    function TextLoader(path) {
      this.path = path;
      this.file = path.replace(/^.*\//, '');
      this.rawText = fs.readFileSync(path, 'utf8');
      this.parse();
    }

    TextLoader.prototype.parse = function() {
      var tagsRegexp;
      tagsRegexp = /^#\S+$/gm;
      this.title = this.rawText.match(/.+/)[0];
      this.tags = this.rawText.match(tagsRegexp).join(',').replace(/#/g, '');
      return this.main = marked(this.rawText.replace(tagsRegexp, ''));
    };

    return TextLoader;

  })();

  textLoader = new TextLoader(filePath.text);

  createTemplateLoader = function() {
    var ref, ref1, temp, templateLoader, updateRel, updateTemplateLoader;
    templateLoader = new HTMLLoader('template.html');
    updateRel = function(prevPath, nextFile) {
      var prevLoader;
      prevLoader = new HTMLLoader("../" + prevPath);
      prevLoader.next = nextFile;
      prevLoader.sync();
      return prevLoader.write();
    };
    updateRel(templateLoader.prev, filePath.html);
    updateTemplateLoader = function(templateLoader, nextFile) {
      var oldPrev;
      oldPrev = templateLoader.prev;
      templateLoader.prev = nextFile;
      templateLoader.sync();
      templateLoader.write();
      return templateLoader.prev = oldPrev;
    };
    updateTemplateLoader(templateLoader, filePath.html);
    temp = filePath.html.replace('^.*/', '');
    ref = [temp, templateLoader.prev], templateLoader.prev = ref[0], temp = ref[1];
    templateLoader.sync();
    templateLoader.write();
    ref1 = [temp, templateLoader.prev], templateLoader.prev = ref1[0], temp = ref1[1];
    templateLoader.path = filePath.html;
    templateLoader.update = function(newLoader) {
      HTMLLoader.prototype.update.call(this, newLoader);
      return this.date = (new Date()).toISOString();
    };
    templateLoader.sync = function() {
      HTMLLoader.prototype.sync.call(this);
      return updateRel();
    };
    return templateLoader;
  };

  try {
    htmlLoader = new HTMLLoader(filePath.html);
  } catch (error) {
    err = error;
    console.error(err);
    console.error('no html file, read `template.html`. ');
    htmlLoader = createTemplateLoader();
  } finally {
    htmlLoader.update(textLoader);
    htmlLoader.sync();
    htmlLoader.write();
  }

}).call(this);
