// Generated by CoffeeScript 1.12.1
(function() {
  var TagsDataBase;

  TagsDataBase = (function() {
    function TagsDataBase(path) {
      this.path = path;
      this.file = path.replace(/^.*\//, '');
      this.dataSet = JSON.parse(fs.readFilsSync(path, 'utf8'));
    }

    TagsDataBase.prototype.increment = function(key, times) {
      if (times == null) {
        times = 1;
      }
      if (this.dataSet) {
        return this.dataSet[key] += times;
      } else {
        return this.dataSet[key] = times;
      }
    };

    TagsDataBase.prototype.toString = function() {
      return JSON.stringify(this.dataSet);
    };

    TagsDataBase.prototype.write = function(path) {
      if (path == null) {
        path = this.path;
      }
      return fs.writeFileSync(path, this.toString(), 'utf8');
    };

    return TagsDataBase;

  })();

}).call(this);
