// Generated by CoffeeScript 1.12.1
(function() {
  var TagsDataBase;

  TagsDataBase = (function() {
    function TagsDataBase(path) {
      this.path = path;
      this.file = path.replace(/^.*\//, '');
      this.dataSet = JSON.parse(fs.readFileSync(path, 'utf8'));
    }

    TagsDataBase.prototype.increment = function(key, times) {
      if (times == null) {
        times = 1;
      }
      if (this.dataSet[key]) {
        return this.dataSet[key] += times;
      } else {
        return this.dataSet[key] = times;
      }
    };

    TagsDataBase.prototype.toString = function() {
      return JSON.stringify(this.dataSet);
    };

    TagsDataBase.prototype.write = function(path) {
      if (path == null) {
        path = this.path;
      }
      return fs.writeFileSync(path, this.toString(), 'utf8');
    };

    TagsDataBase.prototype.updateFromLoader = function(loader) {
      var i, len, ref, results, tag;
      ref = loader.tags.split(/,/g);
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        tag = ref[i];
        results.push(this.increment(tag));
      }
      return results;
    };

    return TagsDataBase;

  })();

  module.exports = TagsDataBase;

}).call(this);
