// Generated by CoffeeScript 1.12.7
(function() {
  var FileLoaderText, fs, marked;

  fs = require('fs');

  marked = require('marked');

  FileLoaderText = (function() {
    function FileLoaderText(path) {
      this.path = path;
      this.file = path.replace(/^.*\//, '');
      this.rawText = fs.readFileSync(path, 'utf8');
      this.parse();
    }

    FileLoaderText.prototype.parse = function() {
      var ref, tagsRegexp;
      tagsRegexp = /^#\S+$/gm;
      this.title = this.rawText.match(/[^#\n]+/)[0].trim();
      this.tags = (ref = this.rawText.match(tagsRegexp)) != null ? ref.join(',').replace(/#/g, '') : void 0;
      return this.main = marked(this.rawText.replace(tagsRegexp, ''));
    };

    return FileLoaderText;

  })();

  module.exports = FileLoaderText;

}).call(this);
