// Generated by CoffeeScript 1.12.7
(function() {
  var FileLoaderText, fs, marked;

  fs = require('fs');

  marked = require('marked');

  FileLoaderText = (function() {
    function FileLoaderText(path) {
      this.path = path;
      this.file = path.replace(/^.*\//, '');
      this.rawText = fs.readFileSync(path, 'utf8');
      this.parse();
    }

    FileLoaderText.prototype.parse = function() {
      var tagsRegexp;
      tagsRegexp = /(\n#\S+)+\s*$/;
      this.title = this.rawText.match(/[^#\n]+/)[0].trim();
      this.tags = this.rawText.match(tagsRegexp)[0].trim().replace(/#/g, '').split(/\n/g).join(',');
      return this.main = marked(this.rawText.replace(tagsRegexp, ''));
    };

    return FileLoaderText;

  })();

  module.exports = FileLoaderText;

}).call(this);
