// Generated by CoffeeScript 1.12.1
(function() {
  var IndexLoader, cheerio, fs;

  fs = require('fs');

  cheerio = require('cheerio');

  IndexLoader = (function() {
    function IndexLoader(path) {
      this.path = path;
      this.selector = cheerio.load(fs.readFileSync(path, 'utf8'), {
        decodeEntities: false,
        xmlMode: false,
        withDomLvl1: true,
        normalizeWhitespace: false
      });
    }

    IndexLoader.prototype.add = function(loader) {
      var tagsArray;
      tagsArray = loader.tags.split(/,/g);
      if (tagsArray.some(function(tag) {
        return tag === 'hide';
      })) {
        return 'hide post.';
      }
      return this.selector("<article>\n    <h2><a href=\"" + loader.file + "\">" + loader.title + "</a></h2>\n    <small class=\"date\">" + loader.date + "</small>\n    <p>\n    " + loader.description + "\n    </p>\n    <ul>\n    " + (tagsArray.map(function(tag) {
        return "<li>" + tag + "</li>";
      }).join('\n')) + "\n    </ul>\n</atricle>\n<hr>").insertAfter('h1');
    };

    IndexLoader.prototype.write = function(path) {
      if (path == null) {
        path = this.path;
      }
      return fs.writeFileSync(path, this.selector.html(), 'utf8');
    };

    return IndexLoader;

  })();

  module.exports = IndexLoader;

}).call(this);
