#!/usr/bin/env node
// Generated by CoffeeScript 1.12.1
(function() {
  var LoaderByCheerio, cheerio;

  cheerio = require('cheerio');

  LoaderByCheerio = (function() {
    function LoaderByCheerio(HTMLText) {
      this.selector = cheerio.load(HTMLText, {
        decodeEntities: false,
        xmlMode: false,
        withDomLvl1: true,
        normalizeWhitespace: false
      });
    }

    LoaderByCheerio.prototype.date = function(setDate) {
      if (setDate) {
        return this.selector('meta[name=date]').attr('content', setDate);
      } else {
        return this.selector('meta[name=date]').attr('content');
      }
    };

    LoaderByCheerio.prototype.index = function(setIndex) {
      if (setIndex) {
        return this.selector('link[rel=index]').attr('href', setIndex);
      } else {
        return this.selector('link[rel=index]').attr('href');
      }
    };

    LoaderByCheerio.prototype.prev = function(setPrev) {
      if (setPrev) {
        return this.selector('link[rel=prev]').attr('href', setPrev);
      } else {
        return this.selector('link[rel=prev]').attr('href');
      }
    };

    LoaderByCheerio.prototype.next = function(setNext) {
      if (setNext) {
        return this.selector('link[rel=next]').attr('href', setNext);
      } else {
        return this.selector('link[rel=next]').attr('href');
      }
    };

    LoaderByCheerio.prototype.title = function(setTitle) {
      if (setTitle) {
        return this.selector('title').text(setTitle);
      } else {
        return this.selector('title').text();
      }
    };

    LoaderByCheerio.prototype.main = function(setMain) {
      if (setMain) {
        return this.selector('main').html(setMain);
      } else {
        return this.selector('main').html;
      }
    };

    LoaderByCheerio.prototype.tags = function(setTags) {
      if (setTags) {
        return this.selector('meta[name=keywords]').attr('content', setTags);
      } else {
        return this.selector('meta[name=keywords]').attr('content').join(',');
      }
    };

    LoaderByCheerio.prototype.update = function(newText) {
      var i, j, len, len1, mustUpdate, optionalUpdate, ref, ref1, results;
      ref = ['main', 'title', 'tags'];
      for (i = 0, len = ref.length; i < len; i++) {
        mustUpdate = ref[i];
        this[mustUpdate](newText[mustUpdate]());
      }
      ref1 = ['date', 'prev', 'next'];
      results = [];
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        optionalUpdate = ref1[j];
        if (!this[optionalUpdate]()) {
          results.push(this[optionalUpdate](typeof newText[optionalUpdate] === "function" ? newText[optionalUpdate]() : void 0));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    LoaderByCheerio.prototype.toString = function() {
      return this.selector.html();
    };

    return LoaderByCheerio;

  })();

  module.exports = LoaderByCheerio;

}).call(this);
