// Generated by CoffeeScript 1.12.1
(function() {
  var Loader, filename, fs, i, len, printFileItem, ref;

  Loader = require('./LoaderByCheerio');

  fs = require('fs');

  printFileItem = function(filename) {
    var whenFileRead;
    whenFileRead = function(err, data) {
      var i, itemLoader, len, ref, template, templateName;
      if (err) {
        throw err;
      }
      itemLoader = new Loader(data);
      itemLoader.filename = function() {
        return filename;
      };
      template = "<h2><a href=\"{{filename}}\">{{title}}</a></h2>\n<small>{{date}}</small>\n<p>\n{{description}}\n</p>";
      ref = ['filename', 'title', 'date', 'description'];
      for (i = 0, len = ref.length; i < len; i++) {
        templateName = ref[i];
        template = template.replace("{{" + templateName + "}}", itemLoader[templateName]());
      }
      return console.log(template);
    };
    return fs.readFile(filename, 'utf8', whenFileRead);
  };

  ref = process.argv.slice(2);
  for (i = 0, len = ref.length; i < len; i++) {
    filename = ref[i];
    printFileItem(filename);
  }

}).call(this);
