// Generated by CoffeeScript 1.12.1
(function() {
  var Loader, filename, fs, i, len, printFileItem, ref;

  Loader = require('./LoaderByCheerio');

  fs = require('fs');

  printFileItem = function(filename) {
    var whenFileRead;
    whenFileRead = function(err, data) {
      var i, itemLoader, itemTags, len, template, templateName, templateNames;
      if (err) {
        throw err;
      }
      itemLoader = new Loader(data);
      itemLoader.filename = function() {
        return filename;
      };
      itemTags = itemLoader.tags().split(/,/g).map(function(tag) {
        return "<li>" + tag + "</li>";
      }).join('\n');
      itemLoader.tags = function() {
        return itemTags;
      };
      template = "<article>\n<h2><a href=\"{{filename}}\">{{title}}</a></h2>\n<small>{{date}}</small>\n<p>\n{{description}}\n</p>\n<ul>\n{{tags}}\n</ul>\n</article>";
      templateNames = ['filename', 'title', 'date', 'description', 'tags'];
      for (i = 0, len = templateNames.length; i < len; i++) {
        templateName = templateNames[i];
        template = template.replace("{{" + templateName + "}}", itemLoader[templateName]());
      }
      console.log(template);
      return console.log('\n<hr>\n');
    };
    return fs.readFile(filename, 'utf8', whenFileRead);
  };

  ref = process.argv.slice(2);
  for (i = 0, len = ref.length; i < len; i++) {
    filename = ref[i];
    printFileItem(filename);
  }

}).call(this);
