// Generated by CoffeeScript 1.12.1
(function() {
  var HTMLLoader, TextLoader, filePath, htmlLoader, textLoader;

  HTMLLoader = require('./FileLoaderCheerio');

  TextLoader = require('./FileLoaderText');

  filePath = (function() {
    var html, text;
    html = process.argv.slice(-1)[0];
    text = html.replace('../', '../text/').replace('.html', '.txt');
    return {
      text: text,
      html: html
    };
  })();

  textLoader = new TextLoader(filePath.text);

  htmlLoader = new HTMLLoader(filePath.html);

  if (!htmlLoader.date) {
    htmlLoader.date = (new Date()).toISOString();
  }

  htmlLoader.update(textLoader);

  htmlLoader.sync();

  htmlLoader.write();

}).call(this);
