// Generated by CoffeeScript 1.12.1
(function() {
  var HTMLLoader, newHTML, prevHTML, templateHTML, updateRel;

  HTMLLoader = require('./FileLoaderCheerio');

  updateRel = function(oldLoader, rel, newLoader) {
    oldLoader[rel] = newLoader.file;
    oldLoader[rel + "Title"] = newLoader.title;
    oldLoader.sync();
    return oldLoader.write();
  };

  newHTML = new HTMLLoader(process.argv.slice(-1)[0]);

  prevHTML = new HTMLLoader("../" + newHTML.prev);

  updateRel(prevHTML, 'next', newHTML);

  templateHTML = new HTMLLoader('template.html');

  updateRel(templateHTML, 'prev', newHTML);

}).call(this);
