// Generated by CoffeeScript 1.12.1
(function() {
  var HrArticle, article, articleList, i, len, ref;

  HrArticle = (function() {
    var getTagsFromUl;

    getTagsFromUl = function(ul) {
      var i, len, li, ref, results;
      ref = ul.children;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        li = ref[i];
        results.push(li.textContent.trim());
      }
      return results;
    };

    function HrArticle(articleNode) {
      this.node = articleNode;
      this.title = articleNode.getElementsByTagName('h2')[0].textContent.trim();
      this.url = articleNode.getElementsByTagName('h2')[0].children[0].href;
      this.date = new Date(articleNode.getElementsByTagName('small')[0].textContent);
      this.description = articleNode.getElementsByTagName('p')[0].textContent;
      this.tags = getTagsFromUl(articleNode.getElementsByTagName('ul')[0]);
    }

    return HrArticle;

  })();

  articleList = [];

  ref = document.getElementsByTagName('article');
  for (i = 0, len = ref.length; i < len; i++) {
    article = ref[i];
    articleList.push(new HrArticle(article));
  }

  window.articleList = articleList;

}).call(this);
